# Generated by Django 4.1.7 on 2023-02-18 10:24

from django.db import migrations
import room.models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=room.models.TopicField(max_length=200),
        ),
    ]
