# Generated by Django 4.1.7 on 2023-02-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room", "0001_initial"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcomment",
            name="comment_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_owner",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="roomcomment",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="room.room",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="host",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to="user_profile.profile"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="room.topic"
            ),
        ),
    ]
