# Generated by Django 4.1.7 on 2023-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
